Transform: 'AWS::Serverless-2016-10-31'
Resources:
    usersFunction:
        # This resource creates a Lambda function.
        Type: 'AWS::Serverless::Function'
        Properties:
            # This function uses the Nodejs v8.10 runtime.
            Runtime: nodejs12.x
            # This is the Lambda function's handler.
            Handler: index.usersHandler
            # The location of the Lambda function code.
            CodeUri: ./src
            # Event sources to attach to this function. In this case, we are attaching
            # multiple API Gateway endpoints to the Lambda function. The function is
            # called when a HTTP request is made to the API Gateway endpoint.
            Events:
                lambdaGetAllUsers:
                    # Define an API Gateway endpoint that responds to HTTP GET at /users
                    Type: Api
                    Properties:
                        Path: /users
                        Method: GET
                lambdaAddUser:
                    Type: Api
                    Properties:
                        Path: /users
                        Method: POST
                lambdaUpdateUser:
                    Type: Api
                    Properties:
                        Path: /users/{userid}
                        Method: PUT
                lambdaGetUser:
                    Type: Api
                    Properties:
                        Path: /users/{userid}
                        Method: GET
                lambdaDeleteUser:
                    Type: Api
                    Properties:
                        Path: /users/{userid}
                        Method: DELETE                

            Policies:
                # Policies to allow the execution of the indicated actions to the table described in Resource
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/users'
    booksFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            # This function uses the Nodejs v8.10 runtime.
            Runtime: nodejs12.x
            # This is the Lambda function's handler.
            Handler: index.booksHandler
            # The location of the Lambda function code.
            CodeUri: ./src
            # Event sources to attach to this function. In this case, we are attaching
            # multiple API Gateway endpoints to the Lambda function. The function is
            # called when a HTTP request is made to the API Gateway endpoint.
            Events:
                lambdaGetAllBooks:
                    # Define an API Gateway endpoint that responds to HTTP GET at /users
                    Type: Api
                    Properties:
                        Path: /books
                        Method: GET
                lambdaAddBook:
                    Type: Api
                    Properties:
                        Path: /books
                        Method: POST
                lambdaUpdateBook:
                    Type: Api
                    Properties:
                        Path: /books/{bookid}
                        Method: PUT
                lambdaGetBook:
                    Type: Api
                    Properties:
                        Path: /books/{bookid}
                        Method: GET
                lambdaDeleteBook:
                    Type: Api
                    Properties:
                        Path: /books/{bookid}
                        Method: DELETE                

            Policies:
                # Policies to allow the execution of the indicated actions to the table described in Resource
                -   Version: '2012-10-17'
                    Statement: 
                        -   Effect: Allow
                            Action:
                                -   'dynamodb:Scan'
                                -   'dynamodb:DeleteItem'
                                -   'dynamodb:GetItem'
                                -   'dynamodb:PutItem'
                                -   'dynamodb:UpdateItem'
                            Resource:
                                'Fn::Join':
                                    -   ''
                                    -   -   'arn:aws:dynamodb:'
                                        -   Ref: 'AWS::Region'
                                        -   ':'
                                        -   Ref: 'AWS::AccountId'
                                        -   ':table/books'
    booksTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: books
            AttributeDefinitions:
                -   AttributeName: bookid
                    AttributeType: S
            KeySchema:
                -   AttributeName: bookid
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

    usersTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: users
            AttributeDefinitions:
                -   AttributeName: userid
                    AttributeType: S
            KeySchema:
                -   AttributeName: userid
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PublicApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/library/"
